# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfmv < Formula
  desc "Rename Terraform resources and modules and generate moved blocks. You can rename blocks flexibly using Jsonnet.
"
  homepage "https://github.com/suzuki-shunsuke/tfmv"
  version "0.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/suzuki-shunsuke/tfmv/releases/download/v0.2.3/tfmv_darwin_amd64.tar.gz"
      sha256 "fc3fc95a434af7e1b9bc247498d3e6df50944f377c4ca7c40d32c9ba9f6ed27c"

      def install
        bin.install "tfmv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/suzuki-shunsuke/tfmv/releases/download/v0.2.3/tfmv_darwin_arm64.tar.gz"
      sha256 "3be0541c8501a48c68bc6a8cd66d27385eda10e948870836a206df311b642909"

      def install
        bin.install "tfmv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/tfmv/releases/download/v0.2.3/tfmv_linux_amd64.tar.gz"
        sha256 "c02ba6b3e83d034cad86e007945bec44766bd84ba2cf96145787d2afaf42c7bc"

        def install
          bin.install "tfmv"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/tfmv/releases/download/v0.2.3/tfmv_linux_arm64.tar.gz"
        sha256 "02366189b2a917300bfd5b4f22fc7a0d4e2b84c74abe24fb33ba501c483254b6"

        def install
          bin.install "tfmv"
        end
      end
    end
  end

  test do
    system "#{bin}/tfmv --version"
  end
end
