# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfmv < Formula
  desc "Rename Terraform resources and modules and generate moved blocks. You can rename blocks flexibly using Jsonnet.
"
  homepage "https://github.com/suzuki-shunsuke/tfmv"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/suzuki-shunsuke/tfmv/releases/download/v0.1.1/tfmv_darwin_amd64.tar.gz"
      sha256 "bc0eaf56b98ca9fc0de76a824bb015747f142b18ff2c54fe35190036081adbf0"

      def install
        bin.install "tfmv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/suzuki-shunsuke/tfmv/releases/download/v0.1.1/tfmv_darwin_arm64.tar.gz"
      sha256 "b316c5eba73a251f622a56e9cbe74b1334d27a26a1a03e43ca6aaf77eaa336a4"

      def install
        bin.install "tfmv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/tfmv/releases/download/v0.1.1/tfmv_linux_amd64.tar.gz"
        sha256 "31408cf9d8291c3e46309234a96acfacb30b1d3f984a5bc870f518d6c5fb09bf"

        def install
          bin.install "tfmv"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/tfmv/releases/download/v0.1.1/tfmv_linux_arm64.tar.gz"
        sha256 "537a947e5b06e80cdc039de6519ee993b9075798fd78a1d7aba4f0da9a2a8702"

        def install
          bin.install "tfmv"
        end
      end
    end
  end

  test do
    system "#{bin}/tfmv --version"
  end
end
