# This file was generated by GoReleaser. DO NOT EDIT.
cask "tfmv" do
  desc "Rename Terraform resources and modules and generate moved blocks. You can rename blocks flexibly using Jsonnet.
"
  homepage "https://github.com/suzuki-shunsuke/tfmv"
  version "0.2.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tfmv"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/tfmv/releases/download/v0.2.8/tfmv_darwin_amd64.tar.gz"
      sha256 "a56af29957b32aedb50530a7c7c9913f04926d6def20cebcb69f0e1037556c87"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/tfmv/releases/download/v0.2.8/tfmv_darwin_arm64.tar.gz"
      sha256 "50faf6e43f098d7a7cfe76a8e7f05527b5466fd404340bd88db57812fbccc02d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suzuki-shunsuke/tfmv/releases/download/v0.2.8/tfmv_linux_amd64.tar.gz"
      sha256 "db7b63ac6dede5b07340c4d351c7a194dc6d4cd2f8791e3c9dbddd19d70f72bf"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/tfmv/releases/download/v0.2.8/tfmv_linux_arm64.tar.gz"
      sha256 "aacd239f8a1f311c4f89edb91736505682847a33b6aca0e5c8097ddf3f2a07e8"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tfmv"]
    end
  end

  # No zap stanza required
end
