# This file was generated by GoReleaser. DO NOT EDIT.
cask "tfmv" do
  desc "Rename Terraform resources and modules and generate moved blocks. You can rename blocks flexibly using Jsonnet.
"
  homepage "https://github.com/suzuki-shunsuke/tfmv"
  version "0.2.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tfmv"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/tfmv/releases/download/v0.2.7/tfmv_darwin_amd64.tar.gz"
      sha256 "487e6f770dafd52a666bae705e0d5e24cf1468092fe53b66a5534e6e35cf08a6"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/tfmv/releases/download/v0.2.7/tfmv_darwin_arm64.tar.gz"
      sha256 "8292f18fe6b94039af4060e146bbb839533e73da604ccf6384fbc9e212013d34"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suzuki-shunsuke/tfmv/releases/download/v0.2.7/tfmv_linux_amd64.tar.gz"
      sha256 "ac33f89cc526fa31036d1ad8f4f36b8644c4a669f7063ea55372e9cfaeece27d"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/tfmv/releases/download/v0.2.7/tfmv_linux_arm64.tar.gz"
      sha256 "63ad24ae21820e05e65eaf011c26a07cb2ecc88e2d0583c34c2800e1d464bbbb"
    end
  end

  # No zap stanza required
end
