# This file was generated by GoReleaser. DO NOT EDIT.
cask "tfmv" do
  name "tfmv"
  desc "Rename Terraform resources and modules and generate moved blocks. You can rename blocks flexibly using Jsonnet.
"
  homepage "https://github.com/suzuki-shunsuke/tfmv"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tfmv"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/tfmv/releases/download/v#{version}/tfmv_darwin_amd64.tar.gz"
      sha256 "28980b12e0e6f6ed75fceed50ef645b84288627bf59235975faeb9c5f3f550c2"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/tfmv/releases/download/v#{version}/tfmv_darwin_arm64.tar.gz"
      sha256 "9a9b5999bba05ac1abd8d5175f87fdf590e18d1c9502b8bc8e24c60ab2bae298"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suzuki-shunsuke/tfmv/releases/download/v#{version}/tfmv_linux_amd64.tar.gz"
      sha256 "f4e8e93d34f596771d1da4b72812b5e8382ac2a571959ef5d054924419c5a4b8"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/tfmv/releases/download/v#{version}/tfmv_linux_arm64.tar.gz"
      sha256 "8eda4f4eb54d1592e1e2795e19600536ae241e318e51077ef8f6d64717e13679"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tfmv"]
    end
  end

  # No zap stanza required
end
